title: My personal blog - Giorgio Ughini
email: giorgio@ughini.it
description: > # this means to ignore newlines until "baseurl:"
  This is my brand new personal website. I will use it as a blog,
  publishing my important moments, my inspiration, and hosting a
  platform that I can give to anyone interested in any of my work.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://giorgioughini.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Giorgio Ughini # add your name
author-pic: adam-face.jpg
about-author: My name is Giorgio ughini. I’m a student of Information Communication Technology Engineering which loves travel, nature and programming.

# Contact links
email: giorgio@ughini.it
phone: # Add your Phone number
website: giorgioughini.github.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: GiorgioUghini # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: giorgioughini # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
